### ISSUE TITLE
Key presses don't appear in input box anymore in Atom 0.184

### ISSUE THREAD

**Issue by edsko** [moshee/atom-pipe#7]
Just upgraded to Atom 0.184, and now when I open Pipe Run, the input box appears, and I can type and somehow this works because when I press enter the right thing happens, but what I type does not actually show in the input box.

Other packages suffer from this too; for instance, see https://github.com/mkleehammer/atom-incremental-search/issues/26.

**Comment by robru** [comment]
Hmm, I'm seeing this again in atom 0.186. It *works* fine, I just can't see what I'm typing in the input box.
